### ISSUE TITLE
Do we need arduino to run this code.

### ISSUE THREAD

**Issue by singh1114** [girish946/plot-cat#3]
I was trying to run this code on ubuntu 16.04. But wasn't able to get any output and faced some error which made me to think that we need real input from an arduino to get the required result. If no I will post the error here.

**Comment by girish946** [comment]
the main intention of this project was to plot the realtime data from sensors (which is coming over serial port). but to run this code you don't need the serial port. you just have to provide the data to plotcat for plotting. this can be even random data.

for example:

```
#!/usr/bin/env python 
# -*- coding: utf-8 -*-
import sys
from plotcat import *
import random

p = plotter()

data = []

@p.plot_self
def setval():
  data = [random.randint(0,100) for i in range(100)]
  p.lines[0][0].set_data(p.currentAxis, data)

p.set_call_back(setval)
```
