### ISSUE TITLE
Data plotting not real-time

### ISSUE THREAD

**Issue by ishansan** [girish946/plot-cat#6]
Hi.
I am plotting data from an IMU sensor using plot-cat, building on the same code as mentioned in your example. When I start the program, a graph is shown with few data points(maybe upto 100), but they are not real-time. [In a sense - as I move the IMU, the motion should be real time tracked] but what I get instead is a static graph with first few values.

Would appreciate any solution for this incase I am missing something.

![screenshot from 2017-08-06 11-44-56](https://user-images.githubusercontent.com/28399789/29001096-cba1ca40-7a9c-11e7-97a0-78ab6bd742e6.png)

**Comment by girish946** [comment]
hi @ishansan 
could you please elaborate the problem?
Also if the problem is solved please post "how did you solve it?" as it would be helpful for others.
thank you.
